# ============================================
# PayFlow Hub Environment
# ============================================
# Purpose: Hub VPC with shared services (ECR, Secrets Manager, Bastion, EKS)
# Security: Private EKS endpoint only, access via bastion
# Cost: ~$175/month (includes VPC endpoints, EKS, Bastion)
#
# Deployment Order:
# 1. Deploy Hub first (foundation for all other environments)
# 2. Hub creates S3 backend bucket that other environments will use
# 3. Hub creates ECR repositories for container images
# 4. Hub creates bastion host for secure EKS access
#
# Why Hub-and-Spoke:
# - Hub: Shared services accessible by all environments
# - Spokes: Environment-specific workloads (prod, dev)
# - Cost: Share expensive resources (ECR, Secrets Manager) across environments

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    http = {
      source  = "hashicorp/http"
      version = "~> 3.4"
    }
  }

  # S3 Backend: Remote state storage
  # NOTE: Backend bucket must be created manually first (see scripts/terraform/init-backend.sh)
  backend "s3" {
    # Values provided via -backend-config=backend-config.hcl
    # All backend configuration is loaded from backend-config.hcl file
    # This file is generated by scripts/terraform/init-backend.sh
  }
}

# ============================================
# Provider Configuration
# ============================================

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = var.project_name
      Environment = "hub"
      ManagedBy   = "terraform"
      Purpose     = "shared-services"
      CostCenter  = "shared-services"
    }
  }
}

# ============================================
# Data Sources: Auto-Detect User IP
# ============================================
# Purpose: Automatically detect user's public IP for bastion access
# Why: Removes manual step of getting IP and prevents 0.0.0.0/0 misconfigurations
# Fallback: If auto-detection fails, user must provide IP explicitly

data "http" "user_ip" {
  url = "https://api.ipify.org?format=text"

  request_headers = {
    Accept = "text/plain"
  }

  # Retry logic: Try multiple times if network is flaky
  # This makes auto-detection more reliable
}

# ============================================
# Local Variables
# ============================================

locals {
  hub_vpc_cidr = "10.0.0.0/16"

  # Backend bucket name will be provided via terraform.tfvars
  # This removes the hardcoded value and makes it configurable
  backend_bucket = var.terraform_state_bucket

  # Automatically detect user's IP if not explicitly provided
  # Priority: 1. User-provided value, 2. Auto-detected IP
  user_ip = try(
    chomp(data.http.user_ip.response_body),
    null
  )

  # Use auto-detected IP if user didn't provide one
  # Validation ensures we have at least one CIDR (either provided or auto-detected)
  bastion_allowed_cidrs = length(var.bastion_allowed_cidrs) > 0 ? var.bastion_allowed_cidrs : (
    local.user_ip != null ? ["${local.user_ip}/32"] : []
  )

  # Validate that we have at least one CIDR (either provided or auto-detected)
  # This ensures security: either user provides IP explicitly, or we auto-detect it
  _bastion_cidr_validation = length(local.bastion_allowed_cidrs) > 0 ? true : (
    error("Could not auto-detect your IP and no bastion_allowed_cidrs provided. Please provide your IP in terraform.tfvars: bastion_allowed_cidrs = [\"YOUR_IP/32\"] or get it with: curl ifconfig.me")
  )

  # Common tags for all resources
  common_tags = {
    Project     = var.project_name
    Environment = "hub"
    ManagedBy   = "terraform"
    Purpose     = "shared-services"
    CostCenter  = "shared-services"
  }

  # EKS node group configuration
  # Hub runs monitoring and ArgoCD workloads (lightweight)
  eks_node_groups = {
    monitoring = {
      instance_types = ["t3.small"] # $15/month per node
      min_size       = 1
      max_size       = 3
      desired_size   = 2
      capacity_type  = "ON_DEMAND" # Stable for monitoring
      disk_size      = 20
    }
  }
}

# ============================================
# Hub VPC: Network Foundation
# ============================================
# Includes: VPC, Subnets, NAT Gateway, VPC Endpoints

module "hub_vpc" {
  source = "../../modules/hub-vpc"

  project_name       = var.project_name
  vpc_cidr           = local.hub_vpc_cidr
  aws_region         = var.aws_region
  availability_zones = var.availability_zones
  single_nat_gateway = var.single_nat_gateway # Cost optimization: single NAT for dev

  tags = local.common_tags
}

# ============================================
# Security Module: Backend Infrastructure
# ============================================
# Creates: S3 backend, DynamoDB locking, ECR, Secrets Manager, Bastion

module "security" {
  source = "../../modules/security"

  project_name      = var.project_name
  environment       = "hub"
  vpc_id            = module.hub_vpc.vpc_id
  public_subnet_ids = module.hub_vpc.public_subnet_ids

  # Backend bucket (created by init-backend.sh)
  terraform_state_bucket = local.backend_bucket

  # EKS cluster ARN: Use wildcard pattern to avoid circular dependency
  # Security is enforced by security group rules, not IAM resource ARN
  eks_cluster_arn = "arn:aws:eks:${var.aws_region}:*:cluster/${var.project_name}-hub-eks"

  # Bastion configuration
  bastion_enabled       = var.enable_bastion_host
  bastion_instance_type = var.bastion_instance_type
  bastion_allowed_cidrs = local.bastion_allowed_cidrs # Use auto-detected IP if not provided
  bastion_key_pair_name = var.bastion_key_pair_name

  # Route53 Private Zone (optional)
  create_private_zone = var.enable_route53_private_dns
  private_zone_name   = "payflow.aws"

  tags = local.common_tags

  depends_on = [module.hub_vpc]
}

# ============================================
# KMS Key: EKS Encryption
# ============================================

resource "aws_kms_key" "eks" {
  description             = "${var.project_name} Hub EKS Secrets Encryption Key"
  deletion_window_in_days = 7
  enable_key_rotation     = true # Security: Rotate key annually

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-hub-eks-key"
  })
}

resource "aws_kms_alias" "eks" {
  name          = "alias/${var.project_name}-hub-eks"
  target_key_id = aws_kms_key.eks.key_id
}

# ============================================
# Hub EKS Cluster: Private Endpoint Only
# ============================================

module "hub_eks" {
  source = "../../modules/eks-cluster"

  project_name              = var.project_name
  environment               = "hub"
  vpc_id                    = module.hub_vpc.vpc_id
  private_subnet_ids        = module.hub_vpc.private_subnet_ids
  kubernetes_version        = var.kubernetes_version
  kms_key_arn               = aws_kms_key.eks.arn
  bastion_security_group_id = module.security.bastion_security_group_id
  node_key_pair_name        = var.bastion_key_pair_name
  node_groups               = local.eks_node_groups

  tags = local.common_tags

  depends_on = [module.hub_vpc, module.security]
}


