# Terraform Backend Configuration for Staging
# This file is automatically generated by setup-terraform-backend.sh

terraform {
  backend "azurerm" {
    resource_group_name  = "terraform-state-rg"
    storage_account_name = "tfstatepayflow123"
    container_name      = "tfstate"
    key                 = "payflow-infra-staging.tfstate"
  }
}
