# Terraform Backend Configuration
# This file is automatically generated by setup-terraform-backend.sh
# DO NOT edit manually - run the setup script to regenerate

terraform {
  backend "azurerm" {
    resource_group_name  = "terraform-state-rg"
    storage_account_name = "tfstatepayflow123"
    container_name       = "tfstate"
    key                  = "payflow-infra.tfstate"

    # Enable state locking and consistency checking
    use_azuread_auth = false # Use storage account key for simplicity

    # Optional: Enable state file encryption at rest
    # encryption_at_rest = true
  }
}

# Note: This backend configuration will be used when you run:
# terraform init
# 
# The backend will be configured to store state in:
# - Resource Group: terraform-state-rg
# - Storage Account: tfstatepayflow123
# - Container: tfstate
# - State File: payflow-infra.tfstate
